### ISSUE TITLE
Adding questionnaires without appointments

### ISSUE THREAD

**Issue by Floraachr** [NeuroDevCo/babylab-redcap#16]
Helloooo sorry the hater is back :)

Sooo: We can only add the questionnaire if we are on the appointment page
For example, we don't have the option to add or modify the language questionnaire if we are on the participant page (but we do have the option to add an appointment) 
We also don't have the option to add a language questionnaire if we are in the questionnaire page (but this one makes maybe more sense, because we don't want to add a language questionnaire by itself but to a participant... Maybe if we have something to create a language questionnaire and then have the option to link it to a participant number? It's maybe a bit complicated for nothing ahah + we don't have that kind of option in the appointment section)

**Comment by gongcastro** [comment]
Te hater is always welcome :)

> For example, we don't have the option to add or modify the language questionnaire if we are on the participant page (but we do have the option to add an appointment)

This is, for now, desired behaviour: since we only get language questionnaires during/after particular appointments, I think it is more organised to have each language questionnaire associated with its corresponding appointment. The app structur does not completely mimic this system, but that's the idea. I do like the option of adding a new questionnaire, selecting the participant/appointment during the process! I'll work on it!

**Comment by gongcastro** [comment]
Solved for now in #22. Now questionnaires can be introduced with an "Estimated" tag.
